### ISSUE TITLE
Various updates for socket.io 0.7

### ISSUE THREAD

**Issue by indexzero** [fat/space-tweet#2]
Not sure if you've seen this, but I've been trying to get this running for the last bit and it seems that there are some significant breaking changes for `socket.io@0.7.x`. 

I'll create a patch and gist it in the comments of this issue when I'm done.

**Comment by indexzero** [comment]
I've created a gist of the patch here: https://gist.github.com/1042087

I have been seeing some strange behavior in socket.io itself which is why I've had to set `force new connection` to be `true`, but maybe @rauchg can chime in on the problem there. 

It seems like `this.sockets` was undefined at this line: https://github.com/LearnBoost/Socket.IO/blob/master/dist/socket.io.js#L91

Anyway, now I'm going to run this through `node-http-proxy`. The sheer volume of this app makes it a great benchmark for the reverse proxy of WebSockets, so thanks!

**Comment by indexzero** [comment]
Ooops! I meant to summon @guille but I used his Twitter handle instead.

**Comment by rauchg** [comment]
The problem is that he's doing `new io.connect` instead of `io.connect`.
More info here: https://github.com/LearnBoost/Socket.IO-node/wiki/Migrating-0.6-to-0.7

**Comment by indexzero** [comment]
@guille Thanks for the tip. Great work on `0.7.x` btw, looks like you've been hard at work :-D

**Comment by fat** [comment]
oh sorry -- yeah i haven't pushed the newest stuff with it working yet! i will in 2 min!

**Comment by fat** [comment]
this should have everything workign again: https://github.com/fat/space-tweet/commit/b77c82338c7eb27700b2bf311a25633c3eebb61c

Sorry again about that !
